import { notifyUpdateReady } from './update'

/**
 * Registers the Workbox service worker generated by vite-plugin-pwa.
 *
 * `vite.config.ts` sets `injectRegister: false` on purpose: registration happens
 * here so the app decides when the worker boots and can tell the reader that a
 * new version has taken over. Production only — there is no `/sw.js` in dev.
 */
export function registerServiceWorker(): void {
  if (!import.meta.env.PROD) {
    return
  }

  if (!('serviceWorker' in navigator)) {
    console.warn('[pwa] service workers are not supported in this browser')
    return
  }

  // Registering after `load` keeps the first paint off the critical path.
  window.addEventListener('load', () => {
    // Whether a worker was already in charge when this page loaded. On a first
    // visit there is none, and the first `controllerchange` is that worker
    // claiming the page — an install, not an update, and reloading for it would
    // be a flash with nothing new behind it.
    const hadController = navigator.serviceWorker.controller !== null

    navigator.serviceWorker.addEventListener('controllerchange', () => {
      if (hadController) {
        notifyUpdateReady()
      }
    })

    navigator.serviceWorker.register('/sw.js', { scope: '/' }).catch((error: unknown) => {
      console.error('[pwa] service worker registration failed', error)
    })
  })
}
