/**
 * Registers the Workbox service worker generated by vite-plugin-pwa.
 *
 * `vite.config.ts` sets `injectRegister: false` on purpose: registration happens
 * here so the app decides when the worker boots and can add update UI later.
 * Production only — there is no `/sw.js` in dev unless `devOptions.enabled` is
 * turned on.
 */
export function registerServiceWorker(): void {
  if (!import.meta.env.PROD) {
    return
  }

  if (!('serviceWorker' in navigator)) {
    console.warn('[pwa] service workers are not supported in this browser')
    return
  }

  // Registering after `load` keeps the first paint off the critical path.
  window.addEventListener('load', () => {
    navigator.serviceWorker
      .register('/sw.js', { scope: '/' })
      .catch((error: unknown) => {
        console.error('[pwa] service worker registration failed', error)
      })
  })
}
